# Generated by Django 3.2.11 on 2022-01-27 03:54

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import slugger.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='users', serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=50, unique=True)),
                ('second_name', models.CharField(max_length=50, unique=True)),
                ('profile_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bio', models.TextField()),
                ('joined_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-joined_on'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', slugger.fields.AutoSlugField(populate_from='title')),
                ('post_thumbnail', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('content', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('post_author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='app.userprofile')),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenting_user', to='app.userprofile')),
                ('comment_post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_post', to='app.posts')),
            ],
            options={
                'ordering': ['-commented_on'],
            },
        ),
    ]
